### ISSUE TITLE
MPI errors

### ISSUE THREAD

**Issue by tariqyasin** [johannesulf/nautilus#61]
Hello. I am getting rather cryptic errors when running the  Nautilus MPI example (https://nautilus-sampler.readthedocs.io/en/latest/guides/parallelization.html) with mpi4py==4.0.0 or 4.0.1 and the latest openmpi 5.0.x. Is there an  MPI version you are able to recommend that Nautilus has been tested with? Apart from Nautilus the MPI installation seems to work correctly. Error shown below. Thanks.

> Traceback (most recent call last):
>   File "/usr/local/shared/python/3.11.4/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
> Exception in thread Thread-1 (_manager_spawn):
> Traceback (most recent call last):
>   File "/usr/local/shared/python/3.11.4/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
>     self.run()
>   File "/usr/local/shared/python/3.11.4/lib/python3.11/threading.py", line 975, in run
>     self.run()
>   File "/usr/local/shared/python/3.11.4/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
>     self._target(*self._args, **self._kwargs)
>   File "/mnt/users/yasin/.virtualenvs/jamhmc/lib/python3.11/site-packages/mpi4py/futures/_core.py", line 350, in _manager_spawn
>   File "/mnt/users/yasin/.virtualenvs/jamhmc/lib/python3.11/site-packages/mpi4py/futures/_core.py", line 350, in _manager_spawn
>     comm = serialized(client_spawn)(pyexe, pyargs, nprocs, info)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     comm = serialized(client_spawn)(pyexe, pyargs, nprocs, info)
>   File "/mnt/users/yasin/.virtualenvs/jamhmc/lib/python3.11/site-packages/mpi4py/futures/_core.py", line 1058, in client_spawn
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/users/yasin/.virtualenvs/jamhmc/lib/python3.11/site-packages/mpi4py/futures/_core.py", line 1058, in client_spawn
>     comm = MPI.COMM_SELF.Spawn(python_exe, args, max_workers, info)
>     comm = MPI.COMM_SELF.Spawn(python_exe, args, max_workers, info)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "src/mpi4py/MPI.src/Comm.pyx", line 2544, in mpi4py.MPI.Intracomm.Spawn
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "src/mpi4py/MPI.src/Comm.pyx", line 2544, in mpi4py.MPI.Intracomm.Spawn
> mpi4py.MPI.Exception: MPI_ERR_UNKNOWN: unknown error
> mpi4py.MPI.Exception: MPI_ERR_UNKNOWN: unknown error

**Comment by johannesulf** [comment]
@tariqyasin Thanks for reporting the behavior and sorry for taking a bit longer to reply. I'll try to investigate this in the coming weeks. I personally don't use MPI for any nautilus fits, unfortunately. So I cannot recommend any particular MPI version.

**Comment by johannesulf** [comment]
Great! Thanks for the update.
